version: "3.8"
services:
  frontend:
    stdin_open: true
    tty: true
    container_name: frontend-react-app
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules     

